# -*- coding: utf-8 -*-
"""NLP_large_text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/187ame_owqP2b67R6PSh4lqUDBxmnH4s7

# We will use a kaggle text dataset

---

# Imports
"""

# Import Tokenizer and pad_sequences
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Import numpy and pandas
import numpy as np
import pandas as pd

"""# Get the data set from the udacity drive"""

path = tf.keras.utils.get_file('reviews.csv', 
                               'https://drive.google.com/uc?id=13ySLC_ue6Umt9RJYSeM2t-V0kCv-4C-P')
print(path)

# Get the review from the file
# 0 for bad review
# 1 for good review
dataset = pd.read_csv(path)

dataset.head()

# GEt the review from the csv file
reviews = dataset['text'].tolist()

"""# Tokenize the text"""

tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(reviews)

word_index = tokenizer.word_index
print(len(word_index))
print(word_index)

"""# Generate sequences for the reviews"""

sequences = tokenizer.texts_to_sequences(reviews)
padded_sequences = pad_sequences(sequences, padding='post')

print(padded_sequences.shape)

print(reviews[0])

print(padded_sequences[0])

